[package]
name = "scratch_p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
ciborium = "0.2.2"
ecdsa = { version = "0.17.0", features = ["algorithm", "serde"] }
hex = "0.4.3"
k256 = "0.14.0"
serde = { version = "1.0.229", features = ["derive"] }
sha256 = "1.6.0"
tokio = "1.53.1"
uint = "0.10.1"
